### ISSUE TITLE
board design

### ISSUE THREAD

**Issue by Haroldthe24th** [Tempate/litaxx#1]

**Comment by Haroldthe24th** [comment]
![Screenshot_58](https://user-images.githubusercontent.com/40290622/94363668-aad67d80-00bb-11eb-9cc6-e94f180e0a71.jpg)

**Comment by Haroldthe24th** [comment]
thoughts?

**Comment by tempate** [comment]
It looks great!

**Comment by Haroldthe24th** [comment]
Alright, I went ahead and pushed that
I also added new hightlighting 
![Uploading Screenshot_73.jpg…]()
for the squares and they appear with a transition

**Comment by Haroldthe24th** [comment]
![Uploading Screenshot_73.jpg…]()

**Comment by Haroldthe24th** [comment]
thinking about using the light blue from the board as the main color for the website

**Comment by tempate** [comment]
It sounds like a good idea
