### ISSUE TITLE
Refreshing when in game makes you a spectator 

### ISSUE THREAD

**Issue by Haroldthe24th** [Tempate/litaxx#2]

**Comment by usr25** [comment]
We could fix this using either usernames or cookies

**Comment by Haroldthe24th** [comment]
@usr25 cookies sound fine, but wdym usernames?

**Comment by tempate** [comment]
The issue is that right now we're identifying users by their socket's id, which apparently changes when you refresh the page. It could be fixed by giving a token to each user.

**Comment by Haroldthe24th** [comment]
can you not do it based on IP?
@Tempate

**Comment by tempate** [comment]
I guess it could be done, but it's non-standard. The right way is to simply set a token on the session cookies.

**Comment by tempate** [comment]
It's been fixed.
