### ISSUE TITLE
Make a more stylish stone counter

### ISSUE THREAD

**Issue by tempate** [Tempate/litaxx#4]
Improve the stone counter so it doesn't just show the bear count, but a moving bar, like [here](https://i.imgur.com/nKDAhpn.mp4).

**Comment by Haroldthe24th** [comment]
that's very doable, I'll take it up I guess.

**Comment by tempate** [comment]
The question now is: should we keep both counters as they are, remove the numeric one or incorporate both of them somehow?

**Comment by Haroldthe24th** [comment]
closing this issue.
